# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
# For a detailed guide to building and testing on Android, read the docs:
# https://circleci.com/docs/2.0/language-android/ for more details.
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  android: circleci/android@1.0.3

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  android-test:
    parameters:
      system-image:
        type: string
    executor:
      name: android/android-machine
    steps:
      - checkout
      - android/start-emulator-and-run-tests:
          test-command: ./gradlew PrebidDemoKotlin:connectedAndroidTest
          system-image: << parameters.system-image >>
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build:
    # These next lines define the Android machine image executor.
    # See: https://circleci.com/docs/2.0/executor-types/
    parameters:
      buildName:
        type: string
      buildCommand:
        type: string
    executor:
      name: android/android-machine

    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: << parameters.buildName >>
          command: << parameters.buildCommand >>
          
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  test:
    # These next lines define the Android machine image executor.
    # See: https://circleci.com/docs/2.0/executor-types/
    executor:
      name: android/android-machine

    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - checkout
      
      # And finally run the release build
      - run:
          name: Test Frameworks
          command: scripts/testPrebidMobile.sh

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build:
          matrix:
            alias: build-all
            parameters:
              buildName:
                - Build Java Demo App
                - Build Kotlin Demo App
                - Build Internal Test App
                - Build Frameworks
              buildCommand:
                - ./gradlew PrebidDemoJava:build
                - ./gradlew PrebidDemoKotlin:build
                - ./gradlew PrebidInternalTestApp:build
          name: build-<<matrix.buildName>>
      - test
      - android-test:
          matrix:
            alias: android-test-all
            parameters:
              system-image:
                - system-images;android-30;google_apis;x86
                - system-images;android-26;google_apis;x86
          name: android-test-<<matrix.system-image>>
