# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
# For a detailed guide to building and testing on Android, read the docs:
# https://circleci.com/docs/2.0/language-android/ for more details.
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  android: circleci/android@1.0.3
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  android-test:
    executor:
      name: android/android-machine
    steps:
      - checkout
      - android/start-emulator-and-run-tests:
          post-emulator-launch-assemble-command: ./gradlew PrebidDemoKotlin:assembleAndroidTest
          test-command: ./gradlew PrebidDemoKotlin:connectedDebugAndroidTest
          system-image: system-images;android-30;google_apis;x86
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build:
    # These next lines define the Android machine image executor.
    # See: https://circleci.com/docs/2.0/executor-types/
    parameters:
      buildCommand:
        type: string
    executor:
      name: android/android-machine

    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          command: << parameters.buildCommand >>
          
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  test:
    # These next lines define the Android machine image executor.
    # See: https://circleci.com/docs/2.0/executor-types/
    executor:
      name: android/android-machine
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - checkout
      # And finally run the release build
      - run:
          name: Test Frameworks
          command: scripts/testPrebidMobile.sh

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build:
         name: Build Java Demo 
         buildCommand: ./gradlew PrebidDemoJava:assembleDebug
      - build:
          name: Build Internal Test App
          buildCommand: ./gradlew PrebidInternalTestApp:assembleDebug
      - build:
         name: Build PrebidMobile Frameworks
         buildCommand: scripts/buildPrebidMobile.sh -nojar
      - test:
          name: Run Unit Tests - Prebid Mobile
      - android-test:
          name: Run Smoke UI Tests - Demo App Kotlin - Android 11
