[versions]
androidx-annotation = "1.9.1"
androidx-appcompat = "1.3.0"
androidx-constraintlayout = "2.1.4"
androidx-espresso = "3.4.0"
androidx-lifecycle-viewmodel-ktx = "2.5.1"
androidx-lifecycle-extensions = "2.2.0"
androidx-localbroadcastmanager = "1.0.0"
androidx-multidex = "2.0.1"
androidx-navigation = "2.3.1"
androidx-preference-ktx = "1.2.0"
androidx-recyclerview = "1.1.0"
androidx-test-rules = "1.4.0"
androidx-test-runner = "1.4.0"
androidx-uiautomator = "2.2.0"
androidx-vectordrawable-animated = "1.1.0"
apache-camel-json-patch = "3.22.2"
apache-commons-lang3 = "3.7"
applovin-sdk = "13.1.0"
assertj-core = "1.7.0"
exoplayer = "2.15.1"
glide = "4.14.2"
google-play-services-ads = "+"
google-play-services-ads-identifier = "18.0.1"
google-play-services-base = "18.1.0"
gradle = "8.7.3"
gson = "2.8.6"
hamcrest = "2.2"
jackson-databind = "2.14.3"
json = "20180813"
jsonassert = "1.5.0"
junit = "4.13.2"
androidx-junit = "1.1.3"
kotlin-stdlib = "2.1.0"
mockito-core = "5.15.2"
okhttp3 = "4.9.3"
robolectric = "4.12.2"
robotium-solo = "5.5.4"
segmentedcontrol = "1.1.3"

[libraries]
androidx-annotation = { module = 'androidx.annotation:annotation', version.ref = "androidx-annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-espresso-idling-resource = { module = "androidx.test.espresso:espresso-idling-resource", version.ref = "androidx-espresso" }
androidx-espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "androidx-espresso" }
androidx-espresso-web = { module = "androidx.test.espresso:espresso-web", version.ref = "androidx-espresso" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "androidx-lifecycle-extensions" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle-viewmodel-ktx" }
androidx-localbroadcastmanager = { module = "androidx.localbroadcastmanager:localbroadcastmanager", version.ref = "androidx-localbroadcastmanager" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "androidx-multidex" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "androidx-preference-ktx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test-rules" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "androidx-uiautomator" }
androidx-vectordrawable-animated = { module = "androidx.vectordrawable:vectordrawable-animated", version.ref = "androidx-vectordrawable-animated" }
apache-camel-json-patch = { module = "org.apache.camel:camel-json-patch", version.ref = "apache-camel-json-patch" }
apache-commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "apache-commons-lang3" }
applovin-sdk = { module = "com.applovin:applovin-sdk", version.ref = "applovin-sdk" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj-core" }
exoplayer = { module = "com.google.android.exoplayer:exoplayer", version.ref = "exoplayer" }
exoplayer-core = { module = "com.google.android.exoplayer:exoplayer-core", version.ref = "exoplayer" }
extension-ima = { module = "com.google.android.exoplayer:extension-ima", version.ref = "exoplayer" }
exoplayer-ui = { module = "com.google.android.exoplayer:exoplayer-ui", version.ref = "exoplayer" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
google-play-services-ads = { group = "com.google.android.gms", name = "play-services-ads", version.ref = "google-play-services-ads" }
google-play-services-ads-identifier = { module = "com.google.android.gms:play-services-ads-identifier", version.ref = "google-play-services-ads-identifier" }
google-play-services-base = { module = "com.google.android.gms:play-services-base", version.ref = "google-play-services-base" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hamcrest-core = { module = "org.hamcrest:hamcrest-core", version.ref = "hamcrest" }
hamcrest-library = { module = "org.hamcrest:hamcrest-library", version.ref = "hamcrest" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson-databind" }
json = { module = "org.json:json", version.ref = "json" }
jsonassert = { module = "org.skyscreamer:jsonassert", version.ref = "jsonassert" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin-stdlib" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito-core" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp3" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
robotium-solo = { module = "com.jayway.android.robotium:robotium-solo", version.ref = "robotium-solo" }
segmentedcontrol = { module = "com.github.RobertApikyan:SegmentedControl", version.ref = "segmentedcontrol" }
shadows-httpclient = { module = "org.robolectric:shadows-httpclient", version.ref = "robolectric" }
