apply from: 'android.gradle'

dependencies {
    api project(':PrebidMobile-core')
}

dokka {
    dokkaPublications{
        javadoc {
            moduleName.set("Prebid Mobile SDK - Android API Reference")
            outputDirectory.set(layout.buildDirectory.dir("combinedJavadoc"))
            failOnWarning.set(false)
            suppressInheritedMembers.set(false)
            suppressObviousFunctions.set(true)
            offlineMode.set(false)
            dokkaSourceSets.main {
                includes.from(files("module.md"))
                sourceRoots.from(
                        project(":PrebidMobile-core").files("src/main/java") +
                                project(":PrebidMobile-admobAdapters").files("src/main/java") +
                                project(":PrebidMobile-gamEventHandlers").files("src/main/java") +
                                project(":PrebidMobile-maxAdapters").files("src/main/java")
                )
                perPackageOption {
                    matchingRegex.set(
                            "com\\.applovin\\.mediation\\.adapters\\.prebid.*" +
                                    "|org\\.prebid\\.mobile\\.addendum.*" +
                                    "|org\\.prebid\\.mobile\\.configuration.*" +
                                    "|org\\.prebid\\.mobile\\.http.*" +
                                    "|org\\.prebid\\.mobile\\.tasksmanager.*" +
                                    "|org\\.prebid\\.mobile\\.rendering.*" +
                                    "|org\\.prebid\\.mobile\\.eventhandlers\\.utils.*" +
                                    "|org\\.prebid\\.mobile\\.eventhandlers\\.global.*"
                    )
                    suppress.set(true)
                }
            }
        }
    }
}
